 const buttonsList= [
    {
      id: 1,
      shape: "rounded",
      size: "",
      color: "",
      inActive: false,
      isLoading: false,
      content: "Rounded",
    },
    {
      id: 2,
      shape: "square",
      size: "",
      color: "",
      inActive: false,
      isLoading: false,
      content: "Square",
    },
    {
      id: 3,
      shape: "circle",
      size: "",
      color: "",
      inActive: false,
      isLoading: false,
      content: "Circle",
    },
    {
      id: 4,
      shape: "rounded",
      size: "small",
      color: "",
      inActive: false,
      isLoading: false,
      content: "Small",
    },
    {
      id: 5,
      shape: "rounded",
      size: "medium",
      color: "",
      inActive: false,
      isLoading: false,
      content: "Medium",
    },
    {
      id: 6,
      shape: "rounded",
      size: "large",
      color: "",
      inActive: false,
      isLoading: false,
      content: "Large",
    },
    {
      id: 7,
      shape: "rounded",
      size: "",
      color: "primary",
      inActive: false,
      isLoading: false,
      content: "Primary",
    },
    {
      id: 8,
      shape: "rounded",
      size: "",
      color: "secondary",
      inActive: false,
      isLoading: false,
      content: "Secondary",
    },
    {
      id: 9,
      shape: "rounded",
      size: "",
      color: "success",
      inActive: false,
      isLoading: false,
      content: "Success",
    },
    {
      id: 10,
      shape: "rounded",
      size: "",
      color: "warning",
      inActive: false,
      isLoading: false,
      content: "Warning",
    },
    {
      id: 11,
      shape: "rounded",
      size: "",
      color: "error",
      inActive: false,
      isLoading: false,
      content: "Error",
    },
    {
      id: 12,
      shape: "rounded",
      size: "",
      color: "",
      inActive: true,
      isLoading: false,
      content: "Inactive",
    },
    {
      id: 13,
      shape: "rounded",
      size: "",
      color: "",
      inActive: false,
      isLoading: true,
      content: "Loading",
    },
  ];
  export {buttonsList}